### ISSUE TITLE
"jasmine index.spec.js" result => Reference Error: document is not defined

### ISSUE THREAD

**Issue by esrshn** [jessepollak/payment#91]
Randomized with seed 07249
Started
..............F...............FF..............................FFFFFFFFFFFFFFFFFFFFFF

Failures:
1) payment validating card types should validate troy card types
  Message:
    AssertionError [ERR_ASSERTION]: troy
  Stack:
    error properties: Object({ generatedMessage: false, code: 'ERR_ASSERTION', actual: false, expected: true, operator: '==' })
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:114:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

2) payment formatCVC should allow only numbers
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:660:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

3) payment formatCVC should restrict to length <= 4
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:673:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

4) payment formatCardNumber should format cc number correctly when transitioning from one length limit to another
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:507:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

5) payment formatCardNumber should set the card type correctly
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:463:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

6) payment formatCardNumber should restrict characters correctly if `maxLength` exceeds max length for card
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:407:9)
        at <Jasmine>
        at ontimeout (timers.js:482:11)
        at tryOnTimeout (timers.js:317:5)
        at Timer.listOnTimeout (timers.js:277:5)

7) payment formatCardNumber should remove the space after a number being deleted on a backspace
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:448:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

8) payment formatCardNumber should remove a trailing space before a number on backspace 
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:433:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

9) payment formatCardNumber should restrict characters after the length
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:355:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

10) payment formatCardNumber should restrict characters for visa when a `maxLength` parameter is set despite card length can be 19
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:394:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

11) payment formatCardNumber should restrict characters when a visa card number is greater than 19 characters
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:381:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

12) payment formatCardNumber should format cc number correctly
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:420:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

13) payment formatCardNumber should format correctly on paste
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:491:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

14) payment formatCardNumber should restrict non-number characters
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:342:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

15) payment formatCardNumber should restrict characters when a generic card number is 16 characters
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:368:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

16) payment formatCardExpiry should restrict combined expiry fields to length <= 6 digits
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:613:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

17) payment formatCardExpiry should a number after removing a space and a /
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:600:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

18) payment formatCardExpiry should restrict year expiry fields to length <= 4 digits
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:642:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

19) payment formatCardExpiry should remove spaces trailing space and / after removing a number
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:587:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

20) payment formatCardExpiry should format add a 0 to a number > 1 in the month input correctly
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:547:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

21) payment formatCardExpiry should restrict month expiry fields to length <= 2 digits
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:626:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

22) payment formatCardExpiry should format forward slash shorthand correctly
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:561:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

23) payment formatCardExpiry should only allow numbers
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:574:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

24) payment formatCardExpiry should add a slash after two numbers
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:522:9)
        at <Jasmine>
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

25) payment formatCardExpiry should format add a 0 and slash to a number > 1 correctly
  Message:
    ReferenceError: document is not defined
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (D:\GitHub\payment\spec\index.spec.js:535:9)
        at <Jasmine>
        at ontimeout (timers.js:482:11)
        at tryOnTimeout (timers.js:317:5)
        at Timer.listOnTimeout (timers.js:277:5)

84 specs, 25 failures
Finished in 0.437 seconds
Randomized with seed 07249 (jasmine --random=true --seed=07249)

**Comment by esrshn** [comment]
npm install and npm run test result
---------------------------------------

> payment@2.3.0 test D:\GitHub\payment
> karma start --single-run --browsers PhantomJS

Hash: f4683f5fa2953dc3a97c
Version: webpack 1.15.0
Time: 62ms
webpack: Compiled successfully.
webpack: Compiling...
Hash: 89f8ae4b3f50751ffafd
Version: webpack 1.15.0
Time: 643ms
          Asset    Size  Chunks             Chunk Names
tests.bundle.js  324 kB       0  [emitted]  tests.bundle.js
chunk    {0} tests.bundle.js (tests.bundle.js) 113 kB [rendered]
    [0] ./tests.bundle.js 133 bytes {0} [built]
    [1] ./spec .+\.spec\.(js|coffee)?$ 204 bytes {0} [built]
    [2] ./spec/index.spec.coffee 26.4 kB {0} [optional] [built]
    [3] ./~/assert/assert.js 11.7 kB {0} [built]
    [4] ./~/util/util.js 15.6 kB {0} [built]
    [5] ./~/process/browser.js 5.42 kB {0} [built]
    [6] ./~/util/support/isBufferBrowser.js 203 bytes {0} [built]
    [7] ./~/util/~/inherits/inherits_browser.js 672 bytes {0} [built]
    [8] ./src/index.js 18.6 kB {0} [built]
    [9] ./~/qj/lib/index.js 5.75 kB {0} [built]
   [10] ./spec/index.spec.js 28.3 kB {0} [optional] [built]
webpack: Compiled successfully.
[32m19 03 2018 15:51:39.685:INFO [karma]: [39mKarma v0.13.22 server started at http://localhost:9876/
[32m19 03 2018 15:51:39.701:INFO [launcher]: [39mStarting browser PhantomJS
[32m19 03 2018 15:51:41.400:INFO [PhantomJS 2.1.1 (Windows 8.0.0)]: [39mConnected on socket zG7VXa0GsfCnfEsAAAAA with id 35557142
[31mPhantomJS 2.1.1 (Windows 8.0.0) ERROR[39m
  SyntaxError: Unexpected token ')'
  at D:/GitHub/payment/tests.bundle.js:2124 <- webpack:///src/index.js:190:0
PhantomJS 2.1.1 (Windows 8.0.0): Executed 0 of 0[31m ERROR[39m (0.118 secs / 0 secs)
